feat(testing): support checkpath

diff --git a/dist/00-common.in b/dist/00-common.in
--- a/dist/00-common.in
+++ b/dist/00-common.in
@@ -1,4 +1,4 @@
-# Copyright (C) 2018-2019 The Alcove Project Authors.
+# Copyright (c) 2018-2019 The Alcove Project Authors.
 readonly __VERSION__="1"
 readonly COLOR_RESET="\033[0m"
 readonly COLOR_BOLD_RED="\033[1;31m"
@@ -12,7 +12,7 @@ readonly CURSOR_GOTO="\033[%d;%dH"
 : "${pidfile:=""}"
 : "${start_stop_daemon_args:=""}"
 __hack_environ__() {
-if [ -z "${COLUMNS}" ] && [ -z "${LINES}" ]; then
+if isempty "${COLUMNS}" && isempty "${LINES}"; then
 eval "$(resize)"
 fi
 }
@@ -43,6 +43,182 @@ einfo "Usage: <start|stop|reload|restart|status>"
 ;;
 esac
 }
+checkpath() {
+local _option=""
+local _option_mode=""
+local _truncate="no"
+local _umask_old="$(umask)"
+local _status=""
+local _mode=""
+local _owner=""
+local _path=""
+local OPTIND="1"
+local OPTARG=""
+umask 002
+while getopts 'dDfFpm:o:WChqVv' _option; do
+case "${_option}" in
+"d")
+_option_mode="d"
+;;
+"D")
+_option_mode="d"
+_truncate="yes"
+;;
+"f")
+_option_mode="f"
+;;
+"F")
+_option_mode="f"
+_truncate="yes"
+;;
+"p")
+_option_mode="p"
+;;
+"m")
+_mode="$(
+echo "${OPTARG}" | awk -F'[ \t]+' '{
+if (NF == 1) {
+if (${1} ~ /[0-7]{3,4}/) {
+printf("%04d", ${1})
+exit(0)
+}
+}
+exit(1)
+}'
+)"
+if not issuccess; then
+eerror "checkpath: invalid mode '${OPTARG}'!"
+return 1
+fi
+;;
+"o")
+_owner="$(
+echo "${OPTARG}" | awk -F':' '{
+if (NF == 2) {
+printf("%s:%s", ${1}, ${2})
+} else if (NF == 1) {
+printf("%s:%s", ${1}, ${1})
+} else {
+printf("nobody:nobody")
+}
+}'
+)"
+;;
+"W")
+_option_mode="W"
+;;
+esac
+done
+shift "$((OPTIND - 1))"
+for _path in "${@}"; do
+case "${_option_mode}" in
+"d")
+if not isdirectory "${_path}"; then
+einfo "${_path}: creating directory"
+quietly mkdir "${_path}"
+if not issuccess; then
+eend 1
+return 1
+fi
+fi
+if not isempty "${_mode}"; then
+_status="$(stat -c "%a" "${_path}")"
+_status="${_status// /}"
+if [ "${_status}" != "${_mode}" ]; then
+einfo "${_path}: correcting mode"
+quietly chmod "${_mode}" "${_path}"
+fi
+fi
+if not isempty "${_owner}"; then
+_status="$(stat -c "%U:%G" "${_path}")"
+_status="${_status// /}"
+if [ "${_status}" != "${_owner}" ]; then
+einfo "${_path}: correcting owner"
+quietly chown "${_owner}" "${_path}"
+fi
+fi
+;;
+"f")
+if isfile "${_path}"; then
+if yesno "${_truncate}"; then
+einfo "${_path}: truncating file"
+quietly printf "" > "${_path}"
+if not issuccess; then
+eend 1
+return 1
+fi
+fi
+else
+einfo "${_path}: creating file"
+quietly touch "${_path}"
+if not issuccess; then
+eend 1
+return 1
+fi
+fi
+if not isempty "${_mode}"; then
+_status="$(stat -c "%a" "${_path}")"
+_status="${_status// /}"
+if [ "${_status}" != "${_mode}" ]; then
+einfo "${_path}: correcting mode"
+quietly chmod "${_mode}" "${_path}"
+fi
+fi
+if not isempty "${_owner}"; then
+_status="$(stat -c "%U:%G" "${_path}")"
+_status="${_status// /}"
+if [ "${_status}" != "${_owner}" ]; then
+einfo "${_path}: correcting owner"
+quietly chown "${_owner}" "${_path}"
+fi
+fi
+;;
+"p")
+if not ispipe "${_path}"; then
+einfo "${_path}: creating pipe"
+quietly mkfifo "${_path}"
+if not issuccess; then
+eend 1
+return 1
+fi
+fi
+if not isempty "${_mode}"; then
+_status="$(stat -c "%a" "${_path}")"
+_status="${_status// /}"
+if [ "${_status}" != "${_mode}" ]; then
+einfo "${_path}: correcting mode"
+quietly chmod "${_mode}" "${_path}"
+fi
+fi
+if not isempty "${_owner}"; then
+_status="$(stat -c "%U:%G" "${_path}")"
+_status="${_status// /}"
+if [ "${_status}" != "${_owner}" ]; then
+einfo "${_path}: correcting owner"
+quietly chown "${_owner}" "${_path}"
+fi
+fi
+;;
+"W")
+if isexists "${_path}"; then
+if [ -d "${_path}" ]; then
+quietly touch "${_path}/.writable" && \
+quietly rm ${_path}/.writable
+else
+quietly mv "${_path}" ".${_path}.writable" && \
+quietly mv ".${_path}.writable" "${_path}"
+fi
+if issuccess; then
+return 0
+fi
+fi
+eend 1
+return 1
+;;
+esac
+done
+umask "${_umask_old}"
+}
 ebegin() {
 printf " ${COLOR_BOLD_GREEN}*${COLOR_RESET} %s ...\n" "${*}"
 }
@@ -56,7 +232,7 @@ eerror() {
 printf " ${COLOR_BOLD_RED}*${COLOR_RESET} %s\n" "${*}"
 }
 eend() {
-[ "${#}" -lt 1 ] && exit 0
+[ "${#}" -lt 1 ] && return 0
 local _status="${1}"
 shift # skip _status
 __hack_environ__
@@ -64,23 +240,72 @@ if [ "${_status}" = "0" ]; then
 printf "${CURSOR_GOTO}${COLOR_BOLD_BLUE}[ ${COLOR_BOLD_GREEN}ok ${COLOR_BOLD_BLUE}]${COLOR_RESET}\n" \
 "$((LINES - 1))" "$((COLUMNS - 5))"
 else
-if [ -n "${*}" ]; then
+if not isempty "${*}"; then
 eerror "${*}"
 printf "${CURSOR_GOTO}${COLOR_BOLD_BLUE}[ ${COLOR_BOLD_RED}!! ${COLOR_BOLD_BLUE}]${COLOR_RESET}\n" \
 "$((LINES - 1))" "$((COLUMNS - 5))"
-exit 1
+return 1
 else
+printf "${CURSOR_GOTO} ${COLOR_BOLD_RED}*${COLOR_RESET}" \
+"$((LINES - 1))" "0"
 printf "${CURSOR_GOTO}${COLOR_BOLD_BLUE}[ ${COLOR_BOLD_RED}!! ${COLOR_BOLD_BLUE}]${COLOR_RESET}\n" \
 "$((LINES - 1))" "$((COLUMNS - 5))"
-exit 1
+return 1
 fi
 fi
-exit 0
+return 0
+}
+quietly() {
+"${@}" > /dev/null 2>&1
+}
+is() {
+"${@}" && return 0 \
+|| return 1
+}
+not() {
+"${@}" && return 1 \
+|| return 0
+}
+isempty() {
+if [ -z "${*}" ]; then
+return 0
+fi
+return 1
+}
+isexists() {
+if [ -e "${*}" ]; then
+return 0
+fi
+return 1
+}
+isfile() {
+if [ -f "${*}" ]; then
+return 0
+fi
+return 1
+}
+ispipe() {
+if [ -p "${*}" ]; then
+return 0
+fi
+return 1
+}
+isdirectory() {
+if [ -d "${*}" ]; then
+return 0
+fi
+return 1
+}
+issuccess() {
+if [ "${?}" = 0 ]; then
+return 0
+fi
+return 1
 }
 yesno() {
 [ "${#}" -lt 1 ] && return 1
-local value="${1}"
-case "${value}" in
+local _value="${1}"
+case "${_value}" in
 [Yy][Ee][Ss]|[Tt][Rr][Uu][Ee]|[Oo][Nn]|1)
 return 0
 ;;
@@ -93,17 +318,19 @@ start() {
 local _background=""
 ebegin "Starting ${name:-"${0}"}"
 if yesno "${command_background}"; then
-if [ -z "${pidfile}" ]; then
+if isempty "${pidfile}"; then
 eend 1 "command_background option requires a pidfile"
+return 1
 fi
-if [ -z "${command_args_background}" ]; then
+if isempty "${command_args_background}"; then
 eend 1 "command_background option requires a command_args_background"
+return 1
 fi
 _background="--background --make-pidfile"
 fi
-[ -n "${output_logger}" ] &&
+not isempty "${output_logger}" && \
 output_logger_arg="--stdout-logger \"${output_logger}\""
-[ -n "${error_logger}" ] &&
+not isempty "${error_logger}" && \
 error_logger_arg="--stderr-logger \"${error_logger}\""
 start_pre && \
 eval 'start-stop-daemon --start \
@@ -142,18 +369,18 @@ eend "${?}" "Failed to stop ${name:-"${0}"}"
 }
 stop_post() { :; }
 status() {
-local pid=""
-if [ -f "${pidfile}" ]; then
-while read -r pid; do
-if [ -d "/proc/${pid}" ]; then
-einfo "status: running"
+local _pid=""
+if isfile "${pidfile}"; then
+while read -r _pid; do
+if isdirectory "/proc/${_pid}"; then
+einfo "Status: running"
 return 0
 fi
-eerror "status: crashed"
+eerror "Status: crashed"
 return 2
 done < "${pidfile}"
 fi
-einfo "status: stopped"
+einfo "Status: stopped"
 return 1
 }
 restart() {
@@ -162,12 +389,13 @@ stop && start
 reload() { :; }
 __hack_environ__
 __hack_stdout__
-if [ -z "${command}" ]; then
-ewarn "\${command} is empty or not set!"
+if isempty "${command}"; then
+ewarn "WARNING: \${command} is empty or not set!"
 fi
-if [ -z "${pidfile}" ]; then
-ewarn "\${pidfile} is empty or not set!"
+if isempty "${pidfile}"; then
+ewarn "WARNING: \${pidfile} is empty or not set!"
 fi
 if [ "${USER}" != "root" ]; then
-eend 1 "requires root to manage daemons!"
+eend 1 "ERROR: requires root to manage daemons!"
+exit 1
 fi
